### ISSUE TITLE
GPU memory

### ISSUE THREAD

**Issue by lesnikow** [nrimsky/CAA#10]
Hi @nrimsky, thanks for your work!  I read in your paper that you benchmarked using two L4 GPUs.

I tried to run a VM with this hardware using the 13B model, but I am getting GPU OOM errors with the current main branch.

Are there some parallelization, lower precision, or other techniques you are using to fit this 13B model onto the L4 GPU with 24 GB of GPU memory? I'm calculating this 13B model will naively need 26 GB for inference and 52 GB for fine-tuning.

Thank you in advance.

**Comment by nrimsky** [comment]
Currently the 13B model is quantized to float16 [here](https://github.com/nrimsky/CAA/blob/main/llama_wrapper.py#L133). This should fit on a single L40 GPU for inference. I did not finetune the 13B model, only the 7B model (which required 2 L40s, each of which have 80GB RAM, this also in half-precision). You probably need more resources to use the same script for finetuning llama 13B. 

However, you can lower the GPU memory requirements by quantizing to 8bits instead of 16. To do this you can use `bitsandbytes`. Can get rid of the distributed data parallel loading here as well.

(to initialize model)
```
AutoModelForCausalLM.from_pretrained(
    load_in_8bit=True, device_map="auto", # and the usual args
)
``` 

(for 8 bit optimizer)
```
import bitsandbytes as bnb
optimizer = bnb.optim.AdamW8bit(model.parameters(), lr=lr)
```
